# Generated by Django 5.0.3 on 2024-05-01 16:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompany',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
