# Generated by Django 5.0.3 on 2024-09-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
