# Generated by Django 5.0.3 on 2024-05-02 11:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0002_alter_buscompany_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buscompany',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='busroute',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='revenuestatistics',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
