# Generated by Django 5.0.3 on 2024-09-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0003_alter_booking_options_alter_booking_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstatistics',
            name='sold_tickets',
        ),
    ]
