# Generated by Django 5.0.3 on 2024-09-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0004_remove_tripstatistics_sold_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
