# Generated by Django 5.0.3 on 2024-10-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0005_customer_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
