# Generated by Django 5.0.3 on 2024-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0006_alter_customer_address_alter_customer_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='No content'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
