# Generated by Django 5.0.3 on 2024-05-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0007_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='avatar',
        ),
    ]
