# Generated by Django 5.0.3 on 2024-09-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0007_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BusManage.bus'),
        ),
    ]
