# Generated by Django 5.0.3 on 2024-05-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0009_ticket_quantity_ticket_total_price_trip_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='remaining_seats',
            field=models.IntegerField(default=0),
        ),
    ]
