# Generated by Django 5.0.3 on 2024-05-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0012_remove_ticket_payment_method_remove_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_online_booking',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='remaining_seats',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='userticket',
            name='trip',
        ),
        migrations.AddField(
            model_name='ticket',
            name='remaining_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userticket',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BusManage.ticket'),
        ),
    ]
