# Generated by Django 5.0.3 on 2024-05-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0013_remove_ticket_is_online_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManage.trip', unique=True),
        ),
    ]
